services:
  app:
    container_name: TaskManager.Api
    build:
      context: .
      dockerfile: src/TaskManager.Api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    container_name: TaskManager.Database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
